Set up database associations
rjmssevilla/NewKnot-Final-Project pull request #4
Opened 2021-03-29 12:32 UTC by wesleydelacruz

##The Story
This PR connects the multiple models that we use for the project. The photos below visually describe the type of associations that was set up.

**Supplier <> Service association**
![Screen Shot 2021-03-29 at 8 31 01 PM](https://user-images.githubusercontent.com/15170570/112836840-ae2fdd80-90cd-11eb-845b-2138daba816e.png)

**Buyer <> Service association through BuyerService and the Review model**
![Screen Shot 2021-03-29 at 8 30 51 PM](https://user-images.githubusercontent.com/15170570/112836826-a839fc80-90cd-11eb-9693-f2022c7ca5d8.png)

2021-03-29 12:40 UTC, analyn34 approved these changes

2021-03-29 12:42 UTC, analyn34 requested changes
Kindly fix your errors

2021-03-29 12:50 UTC, Weltinio approved these changes

2021-03-29 13:02 UTC, wesleydelacruz commented
> Kindly fix your errors

2021-03-30 11:07 UTC, analyn34 approved these changes

2021-03-30 11:09 UTC, rjmssevilla approved these changes

2021-03-30 11:15 UTC, merged